### ISSUE TITLE
Recursive permutation code runs on local machine, but not in the app. Syntax error.

### ISSUE THREAD

**Issue by beaverrrr** [brpapa/recursion-tree-visualizer#10]
This runs to print permutations in my console, but not in the visualizer app
```
def fn(a, n):               
    if len(a) == n:         
        print(a)            
        return              
        
    for k in range(n):      
        if k not in a:
            a.append(k)
            fn(a, n)
            a.pop()
 
fn(a = [], n = 3)
```
![opera_XD3XDCsQSh](https://user-images.githubusercontent.com/1652025/154633337-8c61cd58-3643-46e6-9dd2-f5c3a2facf9e.png)

**Comment by brpapa** [comment]
Unfortunately, prints to stdout are not permitted inside your function because of the way I've implemented this.
