### ISSUE TITLE
Interpreting strings as variables in python

### ISSUE THREAD

**Issue by foderking** [brpapa/recursion-tree-visualizer#12]
For example, when I use a string "boy", I get an error `boy not defined`.
It is interpreting "boy" as a variable instead of a string.
But if I escape the quotes \\"boy\\" , it works.

**Comment by brpapa** [comment]
Do you have some example function?

**Comment by foderking** [comment]
> Do you have some example function?

literally any function that uses a string

**Comment by brpapa** [comment]
Fixed, thanks guys
