### ISSUE TITLE
Incorrect param values

### ISSUE THREAD

**Issue by FernandoBasso** [brpapa/recursion-tree-visualizer#3]
When I try to visualize a recursive call with a custom function, I get the error “Incorrect param values”.

![image](https://user-images.githubusercontent.com/6560620/110306173-47db0200-7fdc-11eb-8eb3-47e6a5bf5a45.png)

I guess I am doing something wrong. Any help would be appreciated.

Great work on this, by the way. Congrats are in order!

**Comment by brpapa** [comment]
You're completely right. Thanks for your contribution!
I'm already working on fixing it and it will soon be available in production.
