### ISSUE TITLE
"incorret params values" when has default parameters on node.js function

### ISSUE THREAD

**Issue by noghartt** [brpapa/recursion-tree-visualizer#6]
I'm trying to execute this code:
```js
function fn(n, sum = 0, prev = 1) {
    if (n <= 1) return sum;
    return fn(n - 1, prev + sum, sum);
}
```

But, when I'm execute him without the two last parameters, like `fn(5)`, popout an error with the phrase: `Incorrect params values`.

**Comment by brpapa** [comment]
It's fixed. Thanks!
