### ISSUE TITLE
Run code successfully on local machine, But get an error online

### ISSUE THREAD

**Issue by Bollie15** [brpapa/recursion-tree-visualizer#8]
Here is my code:
```python
coins = [25,20,10,5,1]
def fn(i, m):
    if 0 == m:
        return 0
    if len(coins) == i:
        return 0x3f3f3f3f
    ans = 0x3f3f3f3f
    for k in range(m // coins[i] + 1):
        ans = min(ans, fn(i+1,m-coins[i]*k) + k)
    return ans

print(fn(0,40))
```
It can run in jupyterlab
![image](https://user-images.githubusercontent.com/56813612/130074472-020b84dc-7d07-47e7-a1d7-f72a5f2f0cf3.png)

I copy this code to https://recursion.vercel.app/, but it get an error: `Your code outputs the following TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'`
![image](https://user-images.githubusercontent.com/56813612/130074351-703cc9e5-b511-44df-bec1-b849ac90e8af.png)

I don't know why it can not run online. I hope you can help me. Thanks!😊

**Comment by brpapa** [comment]
There was a problem on catching of max recursive calls error. Now it's fixed so you should see the correct error.
